### PR TITLE
Ckan ui#122

### PR DESCRIPTION
**Pull request by BrandonSharratt**

### CODE REVIEW

**Review by SteveChapmanBCDX — COMMENTED** [review]
Can you review the keys to make sure they're consistent?  I'm not sure why there would be tertiary menu keys in the secondary menu (and vice versa).

**Comment by BrandonSharratt** [comment]
The colour flipped during UI/UX design and we didn't flip the classes

**Comment by SteveChapmanBCDX** [comment]
> The colour flipped during UI/UX design and we didn't flip the classes

OK - then should new lines 59 and 65 be "tertiary" rather than "secondary"?

**Comment by BrandonSharratt** [comment]
I've made this change, note that it has no functional change, it does however, make the code more readable.

**Comment by SteveChapmanBCDX** [comment]
Changes look good.  Merging PR.

**Pull request merged**
